version: '3.9'
services:
  keycloak-db:
    image: postgres:latest
    environment:
      - 'POSTGRES_DB=keycloak'
      - 'POSTGRES_USER=keycloak'
      - 'POSTGRES_PASSWORD=keycloak'
    ports:
      - "5000:5432"
    networks:
      - "backend"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    environment:
      - 'KEYCLOAK_USER=admin'
      - 'KEYCLOAK_PASSWORD=admin'
      - 'DB_VENDOR=POSTGRES'
      - 'DB_ADDR=keycloak-db'
      - 'DB_DATABASE=keycloak'
      - 'DB_USER=keycloak'
      - 'DB_PASSWORD=keycloak'
    ports:
      - "8080:8080"
    depends_on:
      keycloak-db:
        condition: service_healthy
    command:
      - "-b 0.0.0.0"
    networks:
      - "backend"


  user-info-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5004:5432'
    networks:
      - "backend"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  user-info-service:
    container_name: user-info-service
    build: .
#    image: user-info-service:latest
    depends_on:
      user-info-db:
        condition: service_healthy
    #      config-server:
    #        condition: service_started
    environment:
      - 'DB_URL=jdbc:postgresql://user-info-db:5432/postgres'
      - 'DB_USERNAME=postgres'
      - 'DB_PASSWORD=password'
      - 'KEYCLOAK_URL=http://keycloak:8080'
      - 'KEYCLOAK_REALM=vehicle-renter'
      - 'SERVER_PORT=8084'
    ports:
      - "8084:8084"
    networks:
      - "backend"

networks:
  backend:
    driver: bridge